[project]
name = "my-py-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "OmkarTerbhai", email = "omkarterbhai@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.3.18",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.0",
    "python-dotenv>=1.2.2",
    "yfinance==1.7.0",
]

[project.scripts]
my-py-proj = "my_py_proj:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
